spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true # Bật show-sql cho phát triển
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    # Đọc mật khẩu từ biến môi trường SPRING_DATASOURCE_PASSWORD
    password: ${SPRING_DATASOURCE_PASSWORD:password} # Có thể để giá trị mặc định là 'password' nếu biến môi trường không có, nhưng tốt nhất là không nên.
    driver-class-name: com.mysql.cj.jdbc.Driver
  # --- Cấu hình OAuth2 Client ---
  security:
    oauth2:
      client:
        registration:
          google:
            # Đọc client-id từ biến môi trường GOOGLE_CLIENT_ID
            client-id: ${GOOGLE_CLIENT_ID}
            # Đọc client-secret từ biến môi trường GOOGLE_CLIENT_SECRET
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
  # --- Kết thúc cấu hình OAuth2 Client ---

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
brevo:
  # Đọc api-key từ biến môi trường BREVO_API_KEY
  api-key: ${BREVO_API_KEY}
app:
  base-url: http://localhost:8080
  email:
    verification-template-id: 3
    defaults:
      login-link: https://my-app.com/login
      service-name: My Application
      company-name: My Company Inc.
      company-address: 456 Tech Road, Silicon Valley
      support-phone: 1-800-SUPPORT
      faq-link: https://my-app.com/faq
      policy-link: https://my-app.com/policy
      company-slogan: Innovating the Future

  # << Cấu hình OAuth2 Redirect >>
  frontend-url: http://localhost:5173 # URL gốc của Frontend (Vue.js)
  oauth2:
    redirect-path: /logincallback # Path trên frontend để xử lý token sau khi redirect
  # << Kết thúc >>

openapi:
  service:
    api-docs: backend-service
    server: http://localhost:${server.port}
    title: Backend service
    version: 1.0.0

# --- Cấu hình JWT ---
jwt:
  expiryMinutes: 60
  expiryDay: 7
  # Đọc accessKey từ biến môi trường JWT_ACCESS_KEY
  accessKey: ${JWT_ACCESS_KEY}
  # Đọc refreshKey từ biến môi trường JWT_REFRESH_KEY
  refreshKey: ${JWT_REFRESH_KEY}
# --- Kết thúc cấu hình JWT ---