spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true # Bật show-sql cho phát triển
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
brevo:
  api-key: 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
app:
  base-url: http://localhost:8080 # URL gốc của ứng dụng của bạn (quan trọng cho link xác thực)
  email:
    verification-template-id: 3  # **QUAN TRỌNG**: Thay bằng ID template xác thực thực tế của bạn trên Brevo
    defaults:
      login-link: https://my-app.com/login
      service-name: My Application # Tên ứng dụng của bạn
      company-name: My Company Inc. # Tên công ty
      company-address: 456 Tech Road, Silicon Valley
      support-phone: 1-800-SUPPORT
      faq-link: https://my-app.com/faq
      policy-link: https://my-app.com/policy
      company-slogan: Innovating the Future
openapi:
  service:
    api-docs: backend-service
    server: http://localhost:${server.port}
    title: Backend service
    version: 1.0.0

# --- Thêm cấu hình JWT ---
jwt:
  # Thời gian hết hạn Access Token (tính bằng phút)
  expiryMinutes: 60 # Ví dụ: 60 phút
  # Thời gian hết hạn Refresh Token (tính bằng ngày)
  expiryDay: 7 # Ví dụ: 7 ngày
  # Khóa bí mật cho Access Token (đọc từ biến môi trường)
  accessKey: Nd2ctQjF/hxvrm4N7iHupT99wF00tcWCJqHgIBi19xo=
  # Khóa bí mật cho Refresh Token (đọc từ biến môi trường)
  refreshKey: cv+Pfs4aPF/ap2L5g8tm2n94EC5V+iv1XFAuDdwkvts=
# --- Kết thúc cấu hình JWT ---