spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/testdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID} # No default value
            client-secret: ${GOOGLE_CLIENT_SECRET} # No default value
            scope:
              - email
              - profile

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
brevo:
  api-key: ${BREVO_API_KEY} # No default value
  sender-email: ${BREVO_SENDER_EMAIL:mnam3239@gmail.com} # Default sender email is likely okay
  sender-name: ${BREVO_SENDER_NAME:Nam Mai}           # Default sender name is likely okay
app:
  base-url: ${APP_BASE_URL:http://localhost:8080}
  email:
    verification-template-id: 3 # Consider externalizing if it changes often
    defaults:
      login-link: https://my-app.com/login
      service-name: My Application
      company-name: My Company Inc.
      company-address: 456 Tech Road, Silicon Valley
      support-phone: 1-800-SUPPORT
      faq-link: https://my-app.com/faq
      policy-link: https://my-app.com/policy
      company-slogan: Innovating the Future

  frontend-url: ${APP_FRONTEND_URL:http://localhost:5173} # URL gốc của Frontend (Vue.js)
  oauth2:
    redirect-path: ${APP_OAUTH2_REDIRECT_PATH:/logincallback} # Path trên frontend để xử lý token sau khi redirect

openapi:
  service:
    api-docs: backend-service
    server: ${APP_BASE_URL:http://localhost:8080} # Use the same base URL variable
    title: Backend service
    version: 1.0.0

jwt:
  expiryMinutes: ${JWT_EXPIRY_MINUTES:60}
  expiryDay: ${JWT_EXPIRY_DAYS:7}
  # Remove default keys as they might be flagged too, generate unique ones per environment
  accessKey: ${JWT_ACCESS_KEY} # No default value
  refreshKey: ${JWT_REFRESH_KEY} # No default value
