spring:
  config:
    activate:
      on-profile: test # Kích hoạt cấu hình này khi profile 'test' chạy

  # --- Cấu hình Datasource H2 cho Test ---
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:

  # --- Cấu hình JPA cho Test ---
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop # Tạo và xóa schema mỗi lần test
    show-sql: false # Tắt log SQL cho gọn (có thể bật nếu cần debug)
    properties:
      hibernate:
        format_sql: true

  # --- Cấu hình OAuth2 Client Giả Lập ---
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: dummy-google-client-id # Giá trị giả
            client-secret: dummy-google-client-secret # Giá trị giả
            scope:
              - email
              - profile

  # --- Devtools (Thường không cần trong CI) ---
  # devtools:
  #   add-properties: true # Có thể bỏ comment nếu bạn thực sự cần

# --- Cấu hình Brevo Giả Lập ---
brevo:
  api-key: dummy-brevo-api-key # Giá trị giả

# --- Cấu hình App cho Test ---
app:
  base-url: http://localhost:8080 # Giá trị test
  email:
    verification-template-id: 1 # Giá trị test
    defaults:
      login-link: https://dummy-test.com/login
      service-name: Test Application
      company-name: Test Company Inc.
      company-address: 123 Test Street
      support-phone: 987654
      faq-link: https://dummy-test.com/faq
      policy-link: https://dummy-test.com/policy
      company-slogan: Testing Rocks
  frontend-url: http://localhost:9999 # Giá trị test
  oauth2:
    redirect-path: /testcallback # Giá trị test

# --- Cấu hình JWT Giả Lập ---
jwt:
  expiryMinutes: 60 # Giá trị test
  expiryDay: 7 # Giá trị test
  accessKey: ZXhhbXBsZS1zZWNyZXQtYWNjZXNzLWtleS1mb3Itand0LXNwcmluZ2Jvb3QxMjM0NTY3ODkw # Key giả đủ dài và hợp lệ (Base64 encoded string)
  refreshKey: ZXhhbXBsZS1zZWNyZXQtcmVmcmVzaC1rZXktZm9yLWp3dC1zcHJpbmdib290MTIzNDU2Nzg5MA== # Key giả đủ dài và hợp lệ (Base64 encoded string)

# --- Cấu hình Springdoc/OpenAPI cho Test ---
# Bạn có thể disable nếu muốn test chạy nhanh hơn
springdoc:
  api-docs:
    enabled: true # Hoặc false
  swagger-ui:
    enabled: true # Hoặc false

openapi:
  service:
    api-docs: backend-service-test # Tên phân biệt cho test
    # Cung cấp giá trị mặc định nếu biến môi trường không có trong CI/test
    server: ${BACKEND_SERVICE:http://localhost:8080}
    title: Backend service (Test)
    version: 1.0.0
