# Tên workflow: Build và test project Java với Maven
name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    # <<<< THÊM KHỐI PERMISSIONS Ở ĐÂY >>>>
    permissions:
      contents: write # Cấp quyền ghi để action dependency submission hoạt động

    # Chạy trên môi trường Ubuntu mới nhất
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code từ repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Cài đặt JDK 17 (Temurin) và cấu hình cache cho Maven
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Step 3: Build project bằng Maven và kích hoạt profile 'test'
      - name: Build with Maven using 'test' profile
        run: mvn -B package -Dspring.profiles.active=test --file pom.xml

      # Step 4 (Optional): Gửi dependency graph lên GitHub cho Dependabot
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@v4
